### PR TITLE
upgrade to angular 7 and fixed observeValuse$ after upgrade to rxjs 6+

### PR DESCRIPTION
**Pull request by ChewieWookie**
Hi,

I took liberty of upgrading your module to angular 7 and also newer versions of other dependencies as I was also upgrading my project. 

It works, maybe it is not done in the most professional way but it works for me just fine.

I also found bug in observeValues$ method. I added pipe, moved takeUntil at the end of pipe to prevent leaks and also changed the way you create observables from events of objects ( Observable.create was not working as before in rxjs 6.3, I changed it to fromEvent function and now it works fine )

Feel free to merge it if you want and think that it will help.

Regards.

### CODE REVIEW

**Comment by ChewieWookie** [comment]
Great :) I cannot merge these changes as I do not have write access. 

Could you do it?

**Comment by manekinekko** [comment]
Sure. I've scheduled this PR to be merged (on my todolist) :)

**Comment by ChewieWookie** [comment]
Great :) Thanks!

**Comment by manekinekko** [comment]
Released: @manekinekko/angular-web-bluetooth@4.0.0.

**Pull request merged**
